repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.12.0
- hooks:
  - id: black
    language_version: python3.12
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.11.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
